"""Independent integer reference kernels used by correctness tests.

These functions deliberately do not import MLIR.  They let unit tests compare
the original tensor-style computation with the scalar loop emitted by vMCU on
thousands of inputs even when the optional IREE Runtime wheel is unavailable.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass


@dataclass(frozen=True)
class ReferenceQuantization:
    """Integer parameters for one independently requantized reference layer."""

    input_zero_point: int
    weight_zero_point: int | Sequence[int]
    output_zero_point: int
    multiplier: Sequence[int]
    shift: Sequence[int]


def _wrap_signed(value: int, bits: int) -> int:
    """Implements MLIR's truncation to a two's-complement signed integer."""
    mask = (1 << bits) - 1
    value &= mask
    return value - (1 << bits) if value & (1 << (bits - 1)) else value


def double_round_scale(value: int, multiplier: int, shift: int) -> int:
    """Evaluates the canonical expanded TOSA ``DOUBLE_ROUND`` sequence.

    The implementation mirrors the i64 arithmetic emitted by the pinned IREE
    preprocessing pipeline, including the sign-dependent second rounding term
    for shifts below 31 and the final i64-to-i32 truncation.
    """
    if not 0 <= multiplier < (1 << 31):
        raise ValueError("multiplier must be in [0, 2^31)")
    if not 1 <= shift <= 62:
        raise ValueError("shift must be in [1, 62]")
    product = value * multiplier
    rounded = product + (1 << (shift - 1))
    if shift < 31:
        rounded += (1 << 30) if value > 0 else -(1 << 30)
    return _wrap_signed(rounded >> shift, 32)


def requantize_i8(
    accumulator: int,
    multiplier: int,
    shift: int,
    output_zero_point: int,
) -> int:
    """Requantizes one accumulator with signed-int8 saturation."""
    scaled = double_round_scale(accumulator, multiplier, shift)
    return max(-128, min(127, scaled + output_zero_point))


def tensor_style_fully_connected(
    inputs: Sequence[Sequence[int]],
    weights: Sequence[Sequence[int]],
    bias: Sequence[int],
    multiplier: Sequence[int],
    shift: Sequence[int],
    input_zero_point: int,
    weight_zero_point: int | Sequence[int],
    output_zero_point: int,
) -> list[list[int]]:
    """Reference the original full-accumulator tensor execution order."""
    rows = len(inputs)
    output_channels = len(weights)
    centered_inputs = [
        [value - input_zero_point for value in inputs[row]] for row in range(rows)
    ]
    centered_weights = []
    for channel, channel_weights in enumerate(weights):
        zero_point = (
            weight_zero_point[channel]
            if not isinstance(weight_zero_point, int)
            else weight_zero_point
        )
        centered_weights.append([value - zero_point for value in channel_weights])
    accumulators = [[int(bias[channel]) for channel in range(output_channels)] for _ in inputs]
    for row in range(rows):
        for channel in range(output_channels):
            accumulators[row][channel] += sum(
                lhs * rhs
                for lhs, rhs in zip(
                    centered_inputs[row], centered_weights[channel], strict=True
                )
            )
    return [
        [
            requantize_i8(
                accumulators[row][channel],
                int(multiplier[channel]),
                int(shift[channel]),
                output_zero_point,
            )
            for channel in range(output_channels)
        ]
        for row in range(rows)
    ]


def emitted_style_fully_connected(
    inputs: Sequence[Sequence[int]],
    weights: Sequence[Sequence[int]],
    bias: Sequence[int],
    multiplier: Sequence[int],
    shift: Sequence[int],
    input_zero_point: int,
    weight_zero_point: int | Sequence[int],
    output_zero_point: int,
) -> list[list[int]]:
    """Reference the scalar reduction order generated by the vMCU emitter."""
    output: list[list[int]] = []
    for row_values in inputs:
        row: list[int] = []
        for channel, channel_weights in enumerate(weights):
            weight_zp = (
                weight_zero_point[channel]
                if not isinstance(weight_zero_point, int)
                else weight_zero_point
            )
            accumulator = int(bias[channel])
            for input_value, weight_value in zip(
                row_values, channel_weights, strict=True
            ):
                accumulator += (input_value - input_zero_point) * (
                    weight_value - weight_zp
                )
            row.append(
                requantize_i8(
                    accumulator,
                    int(multiplier[channel]),
                    int(shift[channel]),
                    output_zero_point,
                )
            )
        output.append(row)
    return output


def pad_nhwc(
    image: list[list[list[int]]],
    padding: tuple[int, int, int, int],
    zero_point: int,
) -> list[list[list[int]]]:
    """Pads one HWC image with the affine input zero-point."""
    top, bottom, left, right = padding
    height, width, channels = len(image), len(image[0]), len(image[0][0])
    padded_width = left + width + right
    padded = [
        [[zero_point for _ in range(channels)] for _ in range(padded_width)]
        for _ in range(top + height + bottom)
    ]
    for h in range(height):
        for w in range(width):
            padded[top + h][left + w] = list(image[h][w])
    return padded


def tensor_style_conv2d(
    image: list[list[list[int]]],
    weights: list[list[list[list[int]]]],
    bias: Sequence[int],
    multiplier: Sequence[int],
    shift: Sequence[int],
    input_zero_point: int,
    weight_zero_point: int | Sequence[int],
    output_zero_point: int,
    stride: tuple[int, int] = (1, 1),
    dilation: tuple[int, int] = (1, 1),
) -> list[list[list[int]]]:
    """Materializes the complete HWC i32 accumulator before requantization."""
    kernel_h, kernel_w = len(weights), len(weights[0])
    input_channels = len(image[0][0])
    output_channels = len(weights[0][0][0])
    output_h = (len(image) - dilation[0] * (kernel_h - 1) - 1) // stride[0] + 1
    output_w = (len(image[0]) - dilation[1] * (kernel_w - 1) - 1) // stride[1] + 1
    accumulators = [
        [[int(bias[c]) for c in range(output_channels)] for _ in range(output_w)]
        for _ in range(output_h)
    ]
    for oh in range(output_h):
        for ow in range(output_w):
            for oc in range(output_channels):
                weight_zp = (
                    weight_zero_point[oc]
                    if not isinstance(weight_zero_point, int)
                    else weight_zero_point
                )
                for kh in range(kernel_h):
                    for kw in range(kernel_w):
                        for ic in range(input_channels):
                            accumulators[oh][ow][oc] += (
                                image[oh * stride[0] + kh * dilation[0]][
                                    ow * stride[1] + kw * dilation[1]
                                ][ic]
                                - input_zero_point
                            ) * (weights[kh][kw][ic][oc] - weight_zp)
    return [
        [
            [
                requantize_i8(
                    accumulators[h][w][c], multiplier[c], shift[c], output_zero_point
                )
                for c in range(output_channels)
            ]
            for w in range(output_w)
        ]
        for h in range(output_h)
    ]


def emitted_style_conv2d(
    image: list[list[list[int]]],
    weights: list[list[list[list[int]]]],
    bias: Sequence[int],
    multiplier: Sequence[int],
    shift: Sequence[int],
    input_zero_point: int,
    weight_zero_point: int | Sequence[int],
    output_zero_point: int,
    stride: tuple[int, int] = (1, 1),
    dilation: tuple[int, int] = (1, 1),
) -> list[list[list[int]]]:
    """Computes/requantizes one Conv2D output at a time like the emitter."""
    kernel_h, kernel_w = len(weights), len(weights[0])
    input_channels = len(image[0][0])
    output_channels = len(weights[0][0][0])
    output_h = (len(image) - dilation[0] * (kernel_h - 1) - 1) // stride[0] + 1
    output_w = (len(image[0]) - dilation[1] * (kernel_w - 1) - 1) // stride[1] + 1
    result = []
    for oh in range(output_h):
        row = []
        for ow in range(output_w):
            pixel = []
            for oc in range(output_channels):
                weight_zp = (
                    weight_zero_point[oc]
                    if not isinstance(weight_zero_point, int)
                    else weight_zero_point
                )
                accumulator = int(bias[oc])
                for kh in range(kernel_h):
                    for kw in range(kernel_w):
                        for ic in range(input_channels):
                            accumulator += (
                                image[oh * stride[0] + kh * dilation[0]][
                                    ow * stride[1] + kw * dilation[1]
                                ][ic]
                                - input_zero_point
                            ) * (weights[kh][kw][ic][oc] - weight_zp)
                pixel.append(
                    requantize_i8(accumulator, multiplier[oc], shift[oc], output_zero_point)
                )
            row.append(pixel)
        result.append(row)
    return result


def tensor_style_depthwise(
    image: list[list[list[int]]],
    weights: list[list[list[int]]],
    bias: Sequence[int],
    multiplier: Sequence[int],
    shift: Sequence[int],
    input_zero_point: int,
    weight_zero_point: int | Sequence[int],
    output_zero_point: int,
    stride: tuple[int, int] = (1, 1),
    dilation: tuple[int, int] = (1, 1),
) -> list[list[list[int]]]:
    """Materializes multiplier-one depthwise accumulators before requantizing."""
    kernel_h, kernel_w = len(weights), len(weights[0])
    channels = len(image[0][0])
    output_h = (len(image) - dilation[0] * (kernel_h - 1) - 1) // stride[0] + 1
    output_w = (len(image[0]) - dilation[1] * (kernel_w - 1) - 1) // stride[1] + 1
    accumulators = [
        [[int(bias[c]) for c in range(channels)] for _ in range(output_w)]
        for _ in range(output_h)
    ]
    for oh in range(output_h):
        for ow in range(output_w):
            for channel in range(channels):
                weight_zp = (
                    weight_zero_point[channel]
                    if not isinstance(weight_zero_point, int)
                    else weight_zero_point
                )
                for kh in range(kernel_h):
                    for kw in range(kernel_w):
                        accumulators[oh][ow][channel] += (
                            image[oh * stride[0] + kh * dilation[0]][
                                ow * stride[1] + kw * dilation[1]
                            ][channel]
                            - input_zero_point
                        ) * (weights[kh][kw][channel] - weight_zp)
    return [
        [
            [
                requantize_i8(
                    accumulators[h][w][c], multiplier[c], shift[c], output_zero_point
                )
                for c in range(channels)
            ]
            for w in range(output_w)
        ]
        for h in range(output_h)
    ]


def emitted_style_depthwise(*args, **kwargs) -> list[list[list[int]]]:
    """Computes depthwise outputs directly; kept separate from tensor storage."""
    image, weights, bias, multiplier, shift = args[:5]
    input_zp, weight_zp, output_zp = args[5:8]
    stride = kwargs.get("stride", (1, 1))
    dilation = kwargs.get("dilation", (1, 1))
    kernel_h, kernel_w, channels = len(weights), len(weights[0]), len(image[0][0])
    output_h = (len(image) - dilation[0] * (kernel_h - 1) - 1) // stride[0] + 1
    output_w = (len(image[0]) - dilation[1] * (kernel_w - 1) - 1) // stride[1] + 1
    output = []
    for oh in range(output_h):
        row = []
        for ow in range(output_w):
            pixel = []
            for channel in range(channels):
                channel_zp = weight_zp[channel] if not isinstance(weight_zp, int) else weight_zp
                accumulator = int(bias[channel])
                for kh in range(kernel_h):
                    for kw in range(kernel_w):
                        accumulator += (
                            image[oh * stride[0] + kh * dilation[0]][
                                ow * stride[1] + kw * dilation[1]
                            ][channel]
                            - input_zp
                        ) * (weights[kh][kw][channel] - channel_zp)
                pixel.append(
                    requantize_i8(accumulator, multiplier[channel], shift[channel], output_zp)
                )
            row.append(pixel)
        output.append(row)
    return output


def _same_quantization_residual_add(
    projection: list[list[list[int]]],
    residual: list[list[list[int]]],
    zero_point: int,
) -> list[list[list[int]]]:
    """Adds same-shaped int8 tensors using the proven IBN residual formula."""
    return [
        [
            [
                max(
                    -128,
                    min(
                        127,
                        (projection[h][w][c] - zero_point)
                        + (residual[h][w][c] - zero_point)
                        + zero_point,
                    ),
                )
                for c in range(len(projection[0][0]))
            ]
            for w in range(len(projection[0]))
        ]
        for h in range(len(projection))
    ]


def tensor_style_inverted_bottleneck(
    image: list[list[list[int]]],
    expansion_weights: list[list[list[list[int]]]],
    expansion_bias: Sequence[int],
    expansion_quantization: ReferenceQuantization,
    depthwise_weights: list[list[list[int]]],
    depthwise_bias: Sequence[int],
    depthwise_quantization: ReferenceQuantization,
    projection_weights: list[list[list[list[int]]]],
    projection_bias: Sequence[int],
    projection_quantization: ReferenceQuantization,
    *,
    depthwise_stride: tuple[int, int] = (1, 1),
    residual: bool = False,
) -> list[list[list[int]]]:
    """Evaluates an IBN by materializing all three conventional layer outputs."""
    expanded = tensor_style_conv2d(
        image,
        expansion_weights,
        expansion_bias,
        expansion_quantization.multiplier,
        expansion_quantization.shift,
        expansion_quantization.input_zero_point,
        expansion_quantization.weight_zero_point,
        expansion_quantization.output_zero_point,
    )
    padded = pad_nhwc(
        expanded,
        (1, 1, 1, 1),
        depthwise_quantization.input_zero_point,
    )
    depthwise = tensor_style_depthwise(
        padded,
        depthwise_weights,
        depthwise_bias,
        depthwise_quantization.multiplier,
        depthwise_quantization.shift,
        depthwise_quantization.input_zero_point,
        depthwise_quantization.weight_zero_point,
        depthwise_quantization.output_zero_point,
        stride=depthwise_stride,
    )
    projection = tensor_style_conv2d(
        depthwise,
        projection_weights,
        projection_bias,
        projection_quantization.multiplier,
        projection_quantization.shift,
        projection_quantization.input_zero_point,
        projection_quantization.weight_zero_point,
        projection_quantization.output_zero_point,
    )
    if not residual:
        return projection
    if depthwise_stride != (1, 1):
        raise ValueError("a shape-preserving residual requires stride 1")
    return _same_quantization_residual_add(
        projection,
        image,
        projection_quantization.output_zero_point,
    )


def emitted_style_inverted_bottleneck_11seg(
    image: list[list[list[int]]],
    expansion_weights: list[list[list[list[int]]]],
    expansion_bias: Sequence[int],
    expansion_quantization: ReferenceQuantization,
    depthwise_weights: list[list[list[int]]],
    depthwise_bias: Sequence[int],
    depthwise_quantization: ReferenceQuantization,
    projection_weights: list[list[list[list[int]]]],
    projection_bias: Sequence[int],
    projection_quantization: ReferenceQuantization,
    *,
    depthwise_stride: tuple[int, int] = (1, 1),
    residual: bool = False,
) -> tuple[list[list[list[int]]], dict[str, int]]:
    """Evaluates the fixed 9×B + 1×C + 1×D vMCU schedule.

    The counters make the no-recursive-recomputation invariant testable: each
    C lane is produced once per output position and immediately contributes to
    every projection output channel before the next expanded-channel chunk.
    """
    input_h, input_w, input_channels = (
        len(image),
        len(image[0]),
        len(image[0][0]),
    )
    expanded_channels = len(expansion_bias)
    output_channels = len(projection_bias)
    if input_channels != output_channels:
        raise ValueError("fixed first-generation D segment requires Cin == Cout")
    if (
        expansion_quantization.output_zero_point
        != depthwise_quantization.input_zero_point
        or depthwise_quantization.output_zero_point
        != projection_quantization.input_zero_point
    ):
        raise ValueError("adjacent IBN affine zero-points must agree")
    if residual and (
        depthwise_stride != (1, 1)
        or expansion_quantization.input_zero_point
        != projection_quantization.output_zero_point
    ):
        raise ValueError("residual IBN requires stride 1 and one activation zero-point")

    output_h = (input_h + 2 - 3) // depthwise_stride[0] + 1
    output_w = (input_w + 2 - 3) // depthwise_stride[1] + 1
    segment_lanes = min(input_channels, output_channels)
    result = [
        [
            [projection_quantization.output_zero_point] * output_channels
            for _ in range(output_w)
        ]
        for _ in range(output_h)
    ]
    counters = {"b_slots": 0, "c_values": 0, "projection_products": 0}

    for oh in range(output_h):
        for ow in range(output_w):
            # D is the sole projection-accumulator segment and remains live
            # across all expanded-channel chunks.
            d_segment = [int(value) for value in projection_bias]
            for chunk in range(0, expanded_channels, segment_lanes):
                # Nine B segments hold one complete 3x3 expansion patch.
                b_segments = [
                    [expansion_quantization.output_zero_point] * segment_lanes
                    for _ in range(9)
                ]
                for patch in range(9):
                    kh, kw = divmod(patch, 3)
                    source_h = oh * depthwise_stride[0] + kh - 1
                    source_w = ow * depthwise_stride[1] + kw - 1
                    for lane in range(segment_lanes):
                        counters["b_slots"] += 1
                        expanded_channel = chunk + lane
                        if (
                            expanded_channel >= expanded_channels
                            or source_h < 0
                            or source_h >= input_h
                            or source_w < 0
                            or source_w >= input_w
                        ):
                            continue
                        weight_zp = (
                            expansion_quantization.weight_zero_point[expanded_channel]
                            if not isinstance(
                                expansion_quantization.weight_zero_point, int
                            )
                            else expansion_quantization.weight_zero_point
                        )
                        accumulator = int(expansion_bias[expanded_channel])
                        for input_channel in range(input_channels):
                            accumulator += (
                                image[source_h][source_w][input_channel]
                                - expansion_quantization.input_zero_point
                            ) * (
                                expansion_weights[0][0][input_channel][expanded_channel]
                                - weight_zp
                            )
                        b_segments[patch][lane] = requantize_i8(
                            accumulator,
                            expansion_quantization.multiplier[expanded_channel],
                            expansion_quantization.shift[expanded_channel],
                            expansion_quantization.output_zero_point,
                        )

                # C is produced once for every valid expanded channel. It is
                # retained while all projection channels consume that value.
                c_segment = [depthwise_quantization.output_zero_point] * segment_lanes
                for lane in range(segment_lanes):
                    expanded_channel = chunk + lane
                    if expanded_channel >= expanded_channels:
                        continue
                    depthwise_weight_zp = (
                        depthwise_quantization.weight_zero_point[expanded_channel]
                        if not isinstance(depthwise_quantization.weight_zero_point, int)
                        else depthwise_quantization.weight_zero_point
                    )
                    accumulator = int(depthwise_bias[expanded_channel])
                    for patch in range(9):
                        kh, kw = divmod(patch, 3)
                        accumulator += (
                            b_segments[patch][lane]
                            - depthwise_quantization.input_zero_point
                        ) * (
                            depthwise_weights[kh][kw][expanded_channel]
                            - depthwise_weight_zp
                        )
                    c_segment[lane] = requantize_i8(
                        accumulator,
                        depthwise_quantization.multiplier[expanded_channel],
                        depthwise_quantization.shift[expanded_channel],
                        depthwise_quantization.output_zero_point,
                    )
                    counters["c_values"] += 1

                for output_channel in range(output_channels):
                    projection_weight_zp = (
                        projection_quantization.weight_zero_point[output_channel]
                        if not isinstance(projection_quantization.weight_zero_point, int)
                        else projection_quantization.weight_zero_point
                    )
                    for lane in range(segment_lanes):
                        expanded_channel = chunk + lane
                        if expanded_channel >= expanded_channels:
                            continue
                        d_segment[output_channel] += (
                            c_segment[lane]
                            - projection_quantization.input_zero_point
                        ) * (
                            projection_weights[0][0][expanded_channel][output_channel]
                            - projection_weight_zp
                        )
                        counters["projection_products"] += 1

            for output_channel in range(output_channels):
                result[oh][ow][output_channel] = requantize_i8(
                    d_segment[output_channel],
                    projection_quantization.multiplier[output_channel],
                    projection_quantization.shift[output_channel],
                    projection_quantization.output_zero_point,
                )
            if residual:
                result[oh][ow] = _same_quantization_residual_add(
                    [[result[oh][ow]]],
                    [[image[oh][ow]]],
                    projection_quantization.output_zero_point,
                )[0][0]
    return result, counters
